version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "senha_admin"
      POSTGRES_DB: management_task
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jeancduasan@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
